#!/bin/bash
set -e

cd "$(dirname "$0")/.."
mkdir -p assets/icons assets/tray assets/sounds

# App icon: 512x512 blue rounded square with "365" text
convert -size 512x512 xc:none \
  -fill "#1f2733" -draw "roundrectangle 0,0,511,511,96,96" \
  -fill "#0078d4" -draw "roundrectangle 32,32,479,479,80,80" \
  -fill white -font Liberation-Sans-Bold -pointsize 200 \
  -gravity center -annotate +0-20 "MS" \
  -fill "#7fd4ff" -font Liberation-Sans-Bold -pointsize 90 \
  -gravity center -annotate +0+90 "365" \
  assets/icons/icon.png

# Tray icons (22x22 for SNI)
convert -size 32x32 xc:none \
  -fill "#1f2733" -draw "roundrectangle 0,0,31,31,8,8" \
  -fill "#0078d4" -draw "roundrectangle 4,4,27,27,6,6" \
  -fill white -font Liberation-Sans-Bold -pointsize 10 \
  -gravity center -annotate +0+0 "M" \
  assets/tray/tray.png

convert assets/tray/tray.png \
  -fill "#e51400" -draw "circle 27,5 30,5" \
  assets/tray/tray-alert.png

# Service icons (48x48 PNG versions used by the sidebar)
declare -A SERVICES=(
  [word]="#2b579a:W"
  [excel]="#217346:X"
  [powerpoint]="#b7472a:P"
  [onedrive]="#0078d4:F"
  [onenote]="#7719aa:N"
)

for svc in "${!SERVICES[@]}"; do
  IFS=':' read -r COLOR LETTER <<< "${SERVICES[$svc]}"
  convert -size 48x48 xc:none \
    -fill "$COLOR" -draw "roundrectangle 0,0,47,47,10,10" \
    -fill white -font Liberation-Sans-Bold -pointsize 28 \
    -gravity center -annotate +0+0 "$LETTER" \
    "assets/icons/${svc}.png"
done

# Notification sounds (simple WAVs using sox if available, else raw python fallback)
if command -v sox >/dev/null 2>&1; then
  sox -n -r 44100 -c 2 assets/sounds/new_message.wav synth 0.4 sine 880 vol 0.4 fade h 0.01 0.3 0.1
  sox -n -r 44100 -c 2 assets/sounds/meeting_started.wav synth 0.6 sine 1046 vol 0.5 fade h 0.01 0.4 0.2
  echo "Sounds generated with sox"
else
  echo "sox not available - sounds will be generated by Node script"
  node -e '
    const fs = require("fs");
    function makeWav(file, freq, dur, vol=0.4) {
      const rate = 44100, n = Math.floor(rate*dur);
      const data = Buffer.alloc(n*2+44);
      data.write("RIFF", 0); data.writeUInt32LE(36+n*2, 4); data.write("WAVE", 8);
      data.write("fmt ", 12); data.writeUInt32LE(16, 16); data.writeUInt16LE(1, 20);
      data.writeUInt16LE(1, 22); data.writeUInt32LE(rate, 24);
      data.writeUInt32LE(rate*2, 28); data.writeUInt16LE(2, 32); data.writeUInt16LE(16, 34);
      data.write("data", 36); data.writeUInt32LE(n*2, 40);
      for (let i=0;i<n;i++) {
        const t = i/rate;
        const env = Math.min(1, Math.min(t/0.01, (dur-t)/0.1));
        const sample = Math.sin(2*Math.PI*freq*t) * vol * env;
        data.writeInt16LE(Math.round(sample*32767), 44+i*2);
      }
      fs.writeFileSync(file, data);
      console.log("Generated", file);
    }
    makeWav("assets/sounds/new_message.wav", 880, 0.4);
    makeWav("assets/sounds/meeting_started.wav", 1046, 0.6);
  '
fi

echo "All assets generated:"
find assets -type f | sort